import type { MishitInputDefinition } from './types'

/**
 * UI-ready metadata for every tunable classifier input.
 *
 * The classifier engine does not import this file. It exists so a future
 * Inputs page can render/edit inputs without scraping algorithm code.
 */
export const MISHIT_INPUT_DEFINITIONS: MishitInputDefinition[] = [
  {
    path: 'sample.provisionalSampleSize',
    label: 'Provisional sample size',
    group: 'Sample maturity',
    scope: 'global_policy',
    kind: 'number',
    description: 'Minimum shots before the classifier can make a provisional call.',
    min: 1,
    step: 1,
  },
  {
    path: 'sample.stableSampleSize',
    label: 'Stable sample size',
    group: 'Sample maturity',
    scope: 'global_policy',
    kind: 'number',
    description: 'Minimum shots before player-specific variability is considered stable.',
    min: 1,
    step: 1,
  },
  {
    path: 'sample.maturePopulationSize',
    label: 'Mature population size',
    group: 'Sample maturity',
    scope: 'global_policy',
    kind: 'number',
    description: 'Population size where refresh cadence can slow down.',
    min: 1,
    step: 1,
  },
  {
    path: 'sample.maxReferenceShots',
    label: 'Reference window',
    group: 'Sample maturity',
    scope: 'global_policy',
    kind: 'number',
    description: 'Maximum recent shots used to define the current player baseline.',
    min: 1,
    step: 1,
  },
  {
    path: 'carry.mishitLossPct',
    label: 'Carry mishit loss %',
    group: 'Carry',
    scope: 'global_policy',
    kind: 'number',
    description: 'Shared starter percentage loss floor before player variability is applied.',
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    path: 'carry.mishitLossFloorYards',
    label: 'Carry mishit floor',
    group: 'Carry',
    scope: 'global_policy',
    kind: 'number',
    description: 'Shared starter absolute carry-loss floor in yards.',
    min: 0,
    step: 1,
  },
  {
    path: 'carry.severeLossPct',
    label: 'Carry severe loss %',
    group: 'Carry',
    scope: 'global_policy',
    kind: 'number',
    description: 'Shared starter severe carry-loss percentage.',
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    path: 'carry.severeLossFloorYards',
    label: 'Carry severe floor',
    group: 'Carry',
    scope: 'global_policy',
    kind: 'number',
    description: 'Shared starter severe absolute carry-loss floor in yards.',
    min: 0,
    step: 1,
  },
  {
    path: 'direction.mishitAbsoluteFloorYards',
    label: 'Directional mishit floor',
    group: 'Direction',
    scope: 'global_policy',
    kind: 'number',
    description: 'Shared starter absolute offline floor before player variability is applied.',
    min: 0,
    step: 1,
  },
  {
    path: 'direction.severeAbsoluteFloorYards',
    label: 'Directional severe floor',
    group: 'Direction',
    scope: 'global_policy',
    kind: 'number',
    description: 'Shared starter severe absolute offline floor.',
    min: 0,
    step: 1,
  },
  {
    path: 'direction.mishitDeviationFromCenterYards',
    label: 'Directional mishit deviation',
    group: 'Direction',
    scope: 'global_policy',
    kind: 'number',
    description: 'Shared starter deviation from the player directional center.',
    min: 0,
    step: 1,
  },
  {
    path: 'direction.severeDeviationFromCenterYards',
    label: 'Directional severe deviation',
    group: 'Direction',
    scope: 'global_policy',
    kind: 'number',
    description: 'Shared starter severe deviation from the player directional center.',
    min: 0,
    step: 1,
  },
  {
    path: 'strike.ballSpeedMishitLossPct',
    label: 'Ball-speed mishit loss %',
    group: 'Strike',
    scope: 'global_policy',
    kind: 'number',
    description: 'Shared starter ball-speed loss percentage.',
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    path: 'strike.ballSpeedSevereLossPct',
    label: 'Ball-speed severe loss %',
    group: 'Strike',
    scope: 'global_policy',
    kind: 'number',
    description: 'Shared starter severe ball-speed loss percentage.',
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    path: 'strike.smashFactorMishitLoss',
    label: 'Smash mishit loss',
    group: 'Strike',
    scope: 'global_policy',
    kind: 'number',
    description: 'Shared starter absolute smash-factor loss.',
    min: 0,
    step: 0.01,
  },
  {
    path: 'strike.smashFactorSevereLoss',
    label: 'Smash severe loss',
    group: 'Strike',
    scope: 'global_policy',
    kind: 'number',
    description: 'Shared starter severe absolute smash-factor loss.',
    min: 0,
    step: 0.01,
  },
  {
    path: 'personalization.enabled',
    label: 'Use player variability',
    group: 'Personalization',
    scope: 'global_policy',
    kind: 'boolean',
    description: 'Allows each player population to widen boundaries using its own robust variability.',
  },
  {
    path: 'personalization.stableBaselineOnly',
    label: 'Require stable baseline',
    group: 'Personalization',
    scope: 'global_policy',
    kind: 'boolean',
    description: 'Prevents variability-based personalization until the player baseline is stable.',
  },
  ...[
    ['carryMadMultiplier', 'Carry'],
    ['directionMadMultiplier', 'Direction'],
    ['ballSpeedMadMultiplier', 'Ball speed'],
    ['smashFactorMadMultiplier', 'Smash factor'],
  ].flatMap(([key, label]) => [
    {
      path: `personalization.${key}.mishit`,
      label: `${label} mishit MAD multiplier`,
      group: 'Personalization',
      scope: 'global_policy' as const,
      kind: 'number' as const,
      description: 'How many player-specific MAD units are required before a mishit boundary can widen.',
      min: 0,
      step: 0.1,
    },
    {
      path: `personalization.${key}.severe`,
      label: `${label} severe MAD multiplier`,
      group: 'Personalization',
      scope: 'global_policy' as const,
      kind: 'number' as const,
      description: 'How many player-specific MAD units are required before a severe boundary can widen.',
      min: 0,
      step: 0.1,
    },
  ]),
]

export const MISHIT_PLAYER_OVERRIDE_DEFINITIONS: MishitInputDefinition[] = [
  ['carry.mishitLossYards', 'Carry mishit boundary', 'Carry'],
  ['carry.severeLossYards', 'Carry severe boundary', 'Carry'],
  ['direction.mishitAbsoluteYards', 'Directional mishit absolute boundary', 'Direction'],
  ['direction.severeAbsoluteYards', 'Directional severe absolute boundary', 'Direction'],
  ['direction.mishitDeviationYards', 'Directional mishit deviation boundary', 'Direction'],
  ['direction.severeDeviationYards', 'Directional severe deviation boundary', 'Direction'],
  ['ballSpeed.mishitLossMph', 'Ball-speed mishit boundary', 'Strike'],
  ['ballSpeed.severeLossMph', 'Ball-speed severe boundary', 'Strike'],
  ['smashFactor.mishitLoss', 'Smash mishit boundary', 'Strike'],
  ['smashFactor.severeLoss', 'Smash severe boundary', 'Strike'],
].map(([path, label, group]) => ({
  path,
  label,
  group,
  scope: 'player_override',
  kind: 'number',
  description: 'Optional player/population-specific floor. Stored outside shared classifier defaults.',
  min: 0,
  step: 0.1,
}))
