// AUTO-GENERATED by tools/generate-course-registration-index.mjs.
// This checked-in stub keeps the module resolvable before the first build.

export const routeHoleHeadingDegreesTrue: Readonly<Record<string, readonly number[]>> = {}

export const getRouteHoleHeadingDegreesTrue = (courseId: string, holeNumber: number): number | null => {
  const headings = routeHoleHeadingDegreesTrue[courseId]
  const heading = headings?.[Math.max(1, Math.min(18, Math.round(holeNumber))) - 1]
  return typeof heading === 'number' && Number.isFinite(heading) ? heading : null
}
