import type { IntelligenceModelDefinition } from '../../contracts'

export const patternStabilityDefinition = {
  id: 'performance.pattern_stability',
  name: 'Pattern Stability',
  version: 'legacy-v1',
  status: 'legacy',
  purpose:
    'Measure whether the recent center of a club pattern remains close to its prior carry/offline baseline.',
  question: 'Is this club producing the same basic pattern recently that it produced before?',
  inputs: [
    'eligible club shots',
    'carry yards',
    'offline yards',
    'shot capture time',
    'session membership',
    'session recency weight',
  ],
  outputs: ['pattern stability score (0-100 or null)', 'human-readable drift note'],
  algorithmSummary: [
    'Build a usable shot set requiring carry, offline, a positive analysis weight, and a timestamp.',
    'Require at least 15 usable shots across at least 2 sessions.',
    'Use up to the 12 newest usable shots as the recent window while preserving at least 5 prior shots.',
    'Calculate recency-weighted carry and offline centers for the recent and prior groups.',
    'Score carry drift against a tolerance equal to max(8 yards, 8% of typical carry).',
    'Score offline drift against a tolerance equal to half of the direction target width; target width is currently 15% of typical carry.',
    'Blend carry-drift and offline-drift scores 50/50.',
    'Shrink the raw score toward 50 until both recent and prior groups reach 10 shots of evidence.',
  ],
  parameters: [
    {
      key: 'recentWindowTargetShots',
      label: 'Recent window target shots',
      description: 'Maximum target size of the recent comparison window.',
      defaultValue: 12,
      editable: true,
      unit: 'shots',
      min: 1,
      step: 1,
    },
    {
      key: 'recentWindowMinShots',
      label: 'Minimum recent shots',
      description: 'Minimum recent evidence required before Pattern Stability can score.',
      defaultValue: 5,
      editable: true,
      unit: 'shots',
      min: 1,
      step: 1,
    },
    {
      key: 'priorBaselineMinShots',
      label: 'Minimum prior shots',
      description: 'Minimum prior evidence required for the comparison baseline.',
      defaultValue: 5,
      editable: true,
      unit: 'shots',
      min: 1,
      step: 1,
    },
    {
      key: 'totalUsableMinShots',
      label: 'Minimum total usable shots',
      description: 'Minimum usable carry/offline observations before Pattern Stability can score.',
      defaultValue: 15,
      editable: true,
      unit: 'shots',
      min: 1,
      step: 1,
    },
    {
      key: 'minDistinctSessions',
      label: 'Minimum distinct sessions',
      description: 'Minimum number of sessions represented by usable shots.',
      defaultValue: 2,
      editable: true,
      unit: 'sessions',
      min: 1,
      step: 1,
    },
    {
      key: 'carryDriftTolerancePct',
      label: 'Carry drift tolerance',
      description: 'Carry-drift tolerance expressed as a percentage of typical carry before the floor is applied.',
      defaultValue: 0.08,
      editable: true,
      unit: 'ratio',
      min: 0,
      step: 0.01,
    },
    {
      key: 'carryDriftToleranceFloorYards',
      label: 'Carry drift tolerance floor',
      description: 'Minimum carry-drift tolerance regardless of club distance.',
      defaultValue: 8,
      editable: true,
      unit: 'yards',
      min: 0,
      step: 1,
    },
    {
      key: 'directionTargetWidthPct',
      label: 'Direction target width',
      description: 'Shared direction-window parameter used to derive Pattern Stability offline-drift tolerance.',
      defaultValue: 0.15,
      editable: true,
      unit: 'ratio',
      min: 0,
      step: 0.01,
    },
    {
      key: 'carryDriftWeight',
      label: 'Carry drift weight',
      description: 'Contribution of carry-center drift to the raw Pattern Stability score.',
      defaultValue: 0.5,
      editable: true,
      unit: 'ratio',
      min: 0,
      max: 1,
      step: 0.05,
    },
    {
      key: 'offlineDriftWeight',
      label: 'Offline drift weight',
      description: 'Contribution of offline-center drift to the raw Pattern Stability score.',
      defaultValue: 0.5,
      editable: true,
      unit: 'ratio',
      min: 0,
      max: 1,
      step: 0.05,
    },
    {
      key: 'fullEvidenceShotsPerWindow',
      label: 'Full evidence shots per window',
      description: 'Recent and prior group size required before the score is no longer shrunk toward neutral.',
      defaultValue: 10,
      editable: true,
      unit: 'shots',
      min: 1,
      step: 1,
    },
    {
      key: 'evidenceAnchorScore',
      label: 'Evidence anchor score',
      description: 'Neutral score toward which low-evidence Pattern Stability results are shrunk.',
      defaultValue: 50,
      editable: true,
      min: 0,
      max: 100,
      step: 1,
    },
  ],
  dependencies: [
    {
      modelId: 'analysis.eligibility',
      relationship: 'Determines which shots and sessions may participate in the model.',
    },
    {
      modelId: 'analysis.session_recency_weight',
      relationship: 'Weights shot centers used in the recent/prior comparison.',
    },
    {
      modelId: 'performance.direction_window',
      relationship: 'Provides targetWidthPct used to derive offline-drift tolerance.',
    },
  ],
  downstreamConsumers: [
    {
      modelId: 'decision.club_confidence',
      relationship: 'Pattern Stability is a weighted component of the aggregate club score.',
    },
    {
      modelId: 'insight.club_review',
      relationship: 'Pattern Stability contributes to explanation and strongest/weakest component insights.',
    },
  ],
  legacyReferences: [
    {
      sourcePath: 'src/lib/scoring.ts',
      symbol: 'buildPatternStabilityScore',
    },
    {
      sourcePath: 'src/lib/confidenceConfig.ts',
      symbol: 'confidenceConfig.patternStability',
    },
    {
      sourcePath: 'src/lib/confidenceConfig.ts',
      symbol: 'confidenceConfig.directionWindow.targetWidthPct',
    },
  ],
  notes: [
    'This definition documents current behavior only. No live calculation has been moved or changed yet.',
    'The legacy implementation contains several hard-coded algorithm values (including the 50/50 blend, evidence anchor of 50, and 10-shot evidence scale) that are not currently represented in confidenceConfig.',
    'confidenceConfig.patternStability also contains fields that the current buildPatternStabilityScore implementation does not consume. Those should be audited rather than assumed to be active.',
  ],
} satisfies IntelligenceModelDefinition
