#!/usr/bin/env python3
"""Build topology-safe Looper course packages from cached OSM snapshots.

V4 makes the runtime contract explicit:
- hole-local [0, 0] is the nearest mapped tee centroid, never an arbitrary
  golf=hole route node;
- true heading is packaged for GSPro-world registration;
- playable/context geometry is intersected with a Shapely route corridor;
- MultiPolygon intersections remain separate polygons instead of being joined
  by synthetic bridge edges;
- no live OSM request is performed by this compiler.

The older v3 packages were generated by an uncommitted corridor clipper and can
produce hundreds of fragments or bridge-looking polygons. V4 is intentionally
checked in and reproducible.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from shapely.geometry import GeometryCollection, LineString, MultiPolygon, Polygon
from shapely.validation import make_valid

import build_osm_course_package as base


DEFAULT_MAX_TEE_ANCHOR_YARDS = 140.0
DEFAULT_CONTEXT_CORRIDOR_YARDS = 110.0
DEFAULT_FAIRWAY_CORRIDOR_YARDS = 85.0
DEFAULT_HAZARD_CORRIDOR_YARDS = 110.0
DEFAULT_SIMPLIFY_YARDS = 0.2
MAX_FAIRWAY_POLYGONS = 120
MAX_ROUGH_POLYGONS = 160
MAX_BUNKER_POLYGONS = 120
MAX_PLAYABLE_POLYGONS = 400


def route_length_yards(route: dict[str, Any]) -> float:
    points = route["geometry"]
    return sum(base.haversine_yards(a, b) for a, b in zip(points, points[1:]))


def feature_distance_to_point_yards(
    feature: dict[str, Any],
    point_latlon: tuple[float, float],
) -> float:
    origin = (0.0, 0.0)
    best = float("inf")
    for geometry in feature["geometries"]:
        polygon_xy = [base.local_east_north_yards(point, point_latlon) for point in geometry]
        if len(polygon_xy) < 3:
            continue
        if base.point_in_polygon(origin, polygon_xy):
            return 0.0
        for a, b in zip(polygon_xy, polygon_xy[1:]):
            best = min(best, base.point_segment_distance(origin, a, b))
    return best


def polygon_parts(geometry: Any) -> Iterable[Polygon]:
    if geometry is None or geometry.is_empty:
        return
    if isinstance(geometry, Polygon):
        yield geometry
        return
    if isinstance(geometry, MultiPolygon):
        for part in geometry.geoms:
            yield from polygon_parts(part)
        return
    if isinstance(geometry, GeometryCollection):
        for part in geometry.geoms:
            yield from polygon_parts(part)


def feature_polygons_local(
    feature: dict[str, Any],
    origin: tuple[float, float],
    forward: tuple[float, float],
    right: tuple[float, float],
) -> list[Polygon]:
    output: list[Polygon] = []
    for geometry in feature["geometries"]:
        points = [base.to_hole_local(point, origin, forward, right) for point in geometry]
        if len(points) < 3:
            continue
        candidate = make_valid(Polygon(points))
        output.extend(part for part in polygon_parts(candidate) if part.area > 0.05)
    return output


def serialize_shape(shape: Any, simplify_yards: float) -> list[list[list[float]]]:
    if shape is None or shape.is_empty:
        return []
    if simplify_yards > 0:
        shape = shape.simplify(simplify_yards, preserve_topology=True)
    polygons: list[list[list[float]]] = []
    for part in polygon_parts(make_valid(shape)):
        if part.area <= 0.05:
            continue
        coordinates = list(part.exterior.coords)
        if len(coordinates) < 4:
            continue
        polygons.append([[round(float(x), 3), round(float(y), 3)] for x, y in coordinates[:-1]])
    return polygons


def union_feature_intersections(
    features: list[dict[str, Any]],
    corridor: Any,
    origin: tuple[float, float],
    forward: tuple[float, float],
    right: tuple[float, float],
    simplify_yards: float,
) -> list[list[list[float]]]:
    polygons: list[list[list[float]]] = []
    for feature in features:
        for polygon in feature_polygons_local(feature, origin, forward, right):
            intersection = polygon.intersection(corridor)
            polygons.extend(serialize_shape(intersection, simplify_yards))
    return polygons


def selected_tee_for_route(
    route: dict[str, Any],
    tees: list[dict[str, Any]],
    max_anchor_yards: float,
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    route_start = route["geometry"][0]
    candidates = sorted(
        (
            {
                "feature": tee,
                "osmId": tee.get("osm_id"),
                "startPolygonGapYards": feature_distance_to_point_yards(tee, route_start),
                "startCentroidGapYards": base.haversine_yards(tee["centroid"], route_start),
            }
            for tee in tees
        ),
        key=lambda item: (item["startPolygonGapYards"], item["startCentroidGapYards"]),
    )
    if not candidates or candidates[0]["startPolygonGapYards"] > max_anchor_yards:
        nearest = candidates[0]["startPolygonGapYards"] if candidates else float("inf")
        raise ValueError(
            f"No mapped tee surface within {max_anchor_yards:.0f} yd of hole route start "
            f"(nearest={nearest:.1f} yd). Refusing route-start fallback."
        )
    return candidates[0]["feature"], candidates


def model_for_hole(
    hole_number: int,
    config: dict[str, Any],
    features: list[dict[str, Any]],
    hole_routes: dict[int, dict[str, Any]],
) -> tuple[dict[str, Any], dict[str, Any]]:
    route = hole_routes[hole_number]
    selection = config.get("selection") or {}
    max_tee_anchor = float(selection.get("maxTeeAnchorDistanceYards", DEFAULT_MAX_TEE_ANCHOR_YARDS))
    context_width = float(selection.get("contextRouteDistanceYards", DEFAULT_CONTEXT_CORRIDOR_YARDS))
    fairway_width = float(selection.get("fairwayCorridorYards", min(DEFAULT_FAIRWAY_CORRIDOR_YARDS, context_width)))
    hazard_width = float(selection.get("hazardCorridorYards", min(DEFAULT_HAZARD_CORRIDOR_YARDS, context_width)))
    simplify_yards = float(selection.get("geometrySimplifyYards", DEFAULT_SIMPLIFY_YARDS))

    greens = [feature for feature in features if feature["kind"] == "green"]
    tees = [feature for feature in features if feature["kind"] == "tee"]
    target_green, green_endpoint_gap = base.select_target_green(route, greens)
    selected_tee, tee_candidates = selected_tee_for_route(route, tees, max_tee_anchor)
    origin, forward, right, heading = base.basis_for_anchors(selected_tee, target_green)

    pin = base.to_hole_local(target_green["centroid"], origin, forward, right)
    route_local = [base.to_hole_local(point, origin, forward, right) for point in route["geometry"]]
    tactical_points = [(0.0, 0.0), *route_local, pin]
    tactical_line = LineString(tactical_points)
    fairway_corridor = tactical_line.buffer(fairway_width, cap_style="round", join_style="round")
    hazard_corridor = tactical_line.buffer(hazard_width, cap_style="round", join_style="round")
    context_corridor = tactical_line.buffer(context_width, cap_style="round", join_style="round")

    by_kind: dict[str, list[dict[str, Any]]] = {}
    for feature in features:
        by_kind.setdefault(feature["kind"], []).append(feature)

    selected_tee_polygons: list[list[list[float]]] = []
    for polygon in feature_polygons_local(selected_tee, origin, forward, right):
        selected_tee_polygons.extend(serialize_shape(polygon, simplify_yards))
    target_green_polygons: list[list[list[float]]] = []
    for polygon in feature_polygons_local(target_green, origin, forward, right):
        target_green_polygons.extend(serialize_shape(polygon, simplify_yards))

    surfaces = {
        "tee": selected_tee_polygons,
        "fairway": union_feature_intersections(
            by_kind.get("fairway", []), fairway_corridor, origin, forward, right, simplify_yards
        ),
        "rough": union_feature_intersections(
            by_kind.get("rough", []), context_corridor, origin, forward, right, simplify_yards
        ),
        "green": target_green_polygons,
        "bunker": union_feature_intersections(
            by_kind.get("bunker", []), hazard_corridor, origin, forward, right, simplify_yards
        ),
        "water": union_feature_intersections(
            by_kind.get("water", []), hazard_corridor, origin, forward, right, simplify_yards
        ),
    }
    surfaces = {kind: polygons for kind, polygons in surfaces.items() if polygons}

    context = {
        kind: union_feature_intersections(
            by_kind.get(kind, []), context_corridor, origin, forward, right, simplify_yards
        )
        for kind in ("woods", "scrub", "grass-context")
    }
    context = {kind: polygons for kind, polygons in context.items() if polygons}

    route_yards = route_length_yards(route)
    hole_config = (config.get("holes") or {}).get(str(hole_number)) or {}
    par = int(hole_config.get("par") or route.get("par") or 0) or None
    reference_yards = float(hole_config.get("targetYards") or route_yards)
    requires_fairway = par != 3

    surface_counts = {kind: len(surfaces.get(kind, [])) for kind in ("tee", "fairway", "rough", "green", "bunker", "water")}
    total_playable = sum(surface_counts.values())
    warnings: list[str] = []
    if surface_counts["fairway"] > MAX_FAIRWAY_POLYGONS:
        warnings.append(f"Fairway fragmentation {surface_counts['fairway']} exceeds {MAX_FAIRWAY_POLYGONS}.")
    if surface_counts["rough"] > MAX_ROUGH_POLYGONS:
        warnings.append(f"Rough fragmentation {surface_counts['rough']} exceeds {MAX_ROUGH_POLYGONS}.")
    if surface_counts["bunker"] > MAX_BUNKER_POLYGONS:
        warnings.append(f"Bunker fragmentation {surface_counts['bunker']} exceeds {MAX_BUNKER_POLYGONS}.")
    if total_playable > MAX_PLAYABLE_POLYGONS:
        warnings.append(f"Playable polygon count {total_playable} exceeds {MAX_PLAYABLE_POLYGONS}.")
    if green_endpoint_gap > 30:
        warnings.append(f"Target green centroid is {green_endpoint_gap:.1f} yd from the OSM hole endpoint.")

    ready = (
        surface_counts["tee"] > 0
        and surface_counts["green"] > 0
        and (not requires_fairway or surface_counts["fairway"] > 0)
        and not any("fragmentation" in warning.lower() or "polygon count" in warning.lower() for warning in warnings)
    )

    corridor_bounds = context_corridor.bounds
    geometry_points = [point for polygons in surfaces.values() for polygon in polygons for point in polygon]
    if not geometry_points:
        raise ValueError(f"Hole {hole_number} produced no playable geometry")

    tee_latlon = selected_tee["centroid"]
    green_latlon = target_green["centroid"]
    model = {
        "hole": hole_number,
        "par": par,
        "referenceYards": round(reference_yards, 1),
        "coordinateFrame": {
            "origin": "selected-tee",
            "headingDegreesTrue": round(heading, 6),
            "selectedTeeOsmId": selected_tee.get("osm_id"),
            "selectedTeeLatLon": [round(tee_latlon[0], 8), round(tee_latlon[1], 8)],
            "targetGreenLatLon": [round(green_latlon[0], 8), round(green_latlon[1], 8)],
        },
        "viewBounds": {
            "minX": round(float(corridor_bounds[0]), 1),
            "minY": round(float(corridor_bounds[1]), 1),
            "maxX": round(float(corridor_bounds[2]), 1),
            "maxY": round(float(corridor_bounds[3]), 1),
        },
        "surfaces": surfaces,
        "context": context,
    }

    nearest_gap = tee_candidates[0]["startPolygonGapYards"]
    diagnostic = {
        "hole": hole_number,
        "par": par,
        "referenceYards": round(reference_yards, 1),
        "anchorMethod": "selected-tee-nearest-route-start",
        "routeLengthYards": round(route_yards, 1),
        "routeLengthResidualYards": round(route_yards - reference_yards, 1),
        "straightTeeToGreenYards": round(math.hypot(pin[0], pin[1]), 1),
        "targetGreenOsmId": target_green.get("osm_id"),
        "greenEndpointGapYards": round(green_endpoint_gap, 1),
        "headingDegreesTrue": round(heading, 2),
        "nearestMappedTeeSurfaceYards": round(nearest_gap, 1),
        "selectedTeeOsmId": selected_tee.get("osm_id"),
        "nearbyTeeCandidates": [
            {
                "osmId": item["osmId"],
                "startPolygonGapYards": round(item["startPolygonGapYards"], 1),
                "startCentroidGapYards": round(item["startCentroidGapYards"], 1),
            }
            for item in tee_candidates[:6]
        ],
        "selectionCorridorYards": context_width,
        "surfacePolygons": surface_counts,
        "contextPolygons": {kind: len(context.get(kind, [])) for kind in ("woods", "scrub", "grass-context")},
        "fairwayRequired": requires_fairway,
        "ready": ready,
        "warnings": warnings,
    }
    return model, diagnostic


def raw_context_source_counts(payload: dict[str, Any]) -> Counter[str]:
    counts: Counter[str] = Counter()
    for element in payload.get("elements", []):
        tags = element.get("tags") or {}
        if tags.get("golf"):
            continue
        natural = tags.get("natural")
        landuse = tags.get("landuse")
        if natural in {"wood", "scrub"}:
            counts[f"natural={natural}"] += 1
        if landuse in {"forest", "grass", "meadow"}:
            counts[f"landuse={landuse}"] += 1
    return counts


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--osm", required=True, type=Path)
    parser.add_argument("--config", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--manifest", required=True, type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    payload = json.loads(args.osm.read_text(encoding="utf-8"))
    config = json.loads(args.config.read_text(encoding="utf-8"))
    if config.get("schemaVersion") != "looper-course-build-config-v1":
        raise SystemExit("Unsupported course build config schema")

    features, hole_routes = base.normalize_osm(payload)
    if sorted(hole_routes) != list(range(1, 19)):
        raise SystemExit(f"Expected OSM golf=hole routes 1-18; got {sorted(hole_routes)}")

    holes: dict[str, Any] = {}
    diagnostics: list[dict[str, Any]] = []
    for hole_number in range(1, 19):
        model, diagnostic = model_for_hole(hole_number, config, features, hole_routes)
        holes[str(hole_number)] = model
        diagnostics.append(diagnostic)

    ready_holes = [item["hole"] for item in diagnostics if item["ready"]]
    generated_at = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    builder_fingerprint = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()
    source_context_counts = raw_context_source_counts(payload)
    osm3s = payload.get("osm3s") or {}

    source_element = config.get("osmCourseElement") or {}
    source_type = source_element.get("type") or "way"
    source_id = source_element.get("id") or config.get("osmCourseWayId")
    source_url = f"https://www.openstreetmap.org/{source_type}/{source_id}" if source_id else "https://www.openstreetmap.org"

    package = {
        "schemaVersion": "looper-static-course-package-v1",
        "courseId": config["courseId"],
        "courseName": config["courseName"],
        "location": config["location"],
        "generatedAt": generated_at,
        "provenance": {
            "geometrySource": "Cached OpenStreetMap/Overpass topology-safe route corridor geometry",
            "attribution": "© OpenStreetMap contributors",
            "sourceUrl": source_url,
            "copyrightUrl": "https://www.openstreetmap.org/copyright",
            "license": "Open Database License (ODbL)",
            "licenseUrl": "https://opendatacommons.org/licenses/odbl/1-0/",
            "fetchedAt": generated_at,
            "sourceBaseTimestamp": osm3s.get("timestamp_osm_base"),
            "sourceElementIdsComplete": True,
            "note": "Static geometry is generated from the preserved OSM snapshot; no live OSM query is required during play.",
        },
        "holes": holes,
    }

    manifest = {
        "schemaVersion": "looper-course-package-validation-v1",
        "courseId": config["courseId"],
        "courseName": config["courseName"],
        "generatedAt": generated_at,
        "compiler": "build_osm_course_package_v4",
        "builderFingerprintSha256": builder_fingerprint,
        "sourceBaseTimestamp": osm3s.get("timestamp_osm_base"),
        "contextSourceStatus": "available" if source_context_counts else "unavailable-in-osm-snapshot",
        "contextSourceTagCounts": dict(sorted(source_context_counts.items())),
        "contextSourceNote": (
            "Standalone OSM context features were present and topology-clipped to the tactical route corridor."
            if source_context_counts
            else "No standalone OSM wood/scrub/forest/meadow/grass context features were present in the preserved snapshot."
        ),
        "readyHoleCount": len(ready_holes),
        "readyHoles": ready_holes,
        "allHolesStaticGeometryReady": len(ready_holes) == 18,
        "registrationStatus": "approximate",
        "registrationNote": "Static geometry is selected-tee-local with true heading packaged; GSPro world alignment still requires runtime validation.",
        "holes": diagnostics,
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(package, indent=2, sort_keys=True), encoding="utf-8")
    args.manifest.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")

    print(json.dumps({
        "course": config["courseName"],
        "compiler": manifest["compiler"],
        "ready_holes": ready_holes,
        "all_ready": len(ready_holes) == 18,
        "output": str(args.output),
        "manifest": str(args.manifest),
    }, indent=2, sort_keys=True))

    if len(ready_holes) != 18:
        raise SystemExit(f"Static geometry failed runtime contract; ready holes: {ready_holes}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
