-- Looper identity + cloud persistence foundation.
-- Intentionally stores structured golf data and diagnostic metadata only.
-- Screenshots / minimap captures must never be stored in these tables.

create extension if not exists citext;

create table if not exists public.allowed_users (
  email citext primary key,
  enabled boolean not null default true,
  is_admin boolean not null default false,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email citext,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bags (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default 'My Bag',
  selected_clubs text[] not null,
  version integer not null default 1,
  is_default boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists bags_one_default_per_user
  on public.bags(user_id)
  where is_default = true;

create table if not exists public.sessions (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  started_at timestamptz not null,
  ended_at timestamptz,
  source text,
  feed_mode text,
  include_in_analysis boolean not null default true,
  schema_version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists sessions_user_started_idx
  on public.sessions(user_id, started_at desc);

create table if not exists public.shots (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid not null references public.sessions(id) on delete cascade,
  captured_at timestamptz not null,
  club text not null,
  included boolean not null default true,
  source text not null,
  enrichment_status text not null,
  shot_variant_id text,
  felt_perfect boolean,
  felt_perfect_tagged_at timestamptz,
  felt_perfect_source text,

  carry_yards double precision,
  total_yards double precision,
  offline_yards double precision,
  ball_speed_mph double precision,
  ball_speed_meters_per_second double precision,
  vertical_launch_angle_degrees double precision,
  horizontal_launch_angle_degrees double precision,
  total_spin_rpm double precision,
  spin_axis_degrees double precision,
  peak_height double precision,
  descent_angle double precision,
  back_spin double precision,
  side_spin double precision,
  club_speed double precision,
  club_path_degrees double precision,
  face_to_path_degrees double precision,
  face_to_target_degrees double precision,
  club_aoa double precision,
  club_lie double precision,
  club_loft double precision,
  dynamic_loft double precision,
  closure_rate double precision,
  club_face_h_impact double precision,
  club_face_v_impact double precision,
  smash_factor double precision,
  distance_to_pin double precision,
  shot_name text,
  shot_ranking text,

  -- Temporary fidelity bridge while localStorage data is migrated. This is golf
  -- interpretation JSON only; never images, screenshots, blobs, or base64.
  open_golf_coach jsonb,

  created_at timestamptz not null default now()
);

create index if not exists shots_user_captured_idx
  on public.shots(user_id, captured_at desc);
create index if not exists shots_session_captured_idx
  on public.shots(session_id, captured_at);

create table if not exists public.diagnostic_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid references public.sessions(id) on delete set null,
  course_key text,
  hole_number integer,
  component text not null,
  model_version text,
  result text not null,
  reason text,
  confidence double precision,
  metadata jsonb,
  created_at timestamptz not null default now(),
  constraint diagnostic_events_no_image_payload check (
    metadata is null
    or not (
      metadata ? 'image'
      or metadata ? 'imageData'
      or metadata ? 'screenshot'
      or metadata ? 'base64'
      or metadata ? 'blob'
    )
  )
);

create index if not exists diagnostic_events_user_created_idx
  on public.diagnostic_events(user_id, created_at desc);
create index if not exists diagnostic_events_failure_idx
  on public.diagnostic_events(component, result, created_at desc);

-- A signed-in identity is considered a Looper user only when its email is explicitly enabled.
create or replace function public.is_allowed_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.allowed_users au
    where au.enabled = true
      and lower(au.email::text) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

revoke all on function public.is_allowed_user() from public;
grant execute on function public.is_allowed_user() to authenticated;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name')
  )
  on conflict (id) do update
    set email = excluded.email,
        display_name = coalesce(excluded.display_name, public.profiles.display_name),
        updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update of email, raw_user_meta_data on auth.users
  for each row execute procedure public.handle_new_auth_user();

alter table public.allowed_users enable row level security;
alter table public.profiles enable row level security;
alter table public.bags enable row level security;
alter table public.sessions enable row level security;
alter table public.shots enable row level security;
alter table public.diagnostic_events enable row level security;

-- Users may only confirm their own allow-list record. Admin management can use
-- the Supabase dashboard/service role initially, and a tiny Looper admin UI later.
create policy "allowed users can read own allowlist row"
  on public.allowed_users for select
  to authenticated
  using (
    lower(email::text) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );

create policy "users can read own profile"
  on public.profiles for select
  to authenticated
  using (id = auth.uid() and public.is_allowed_user());

create policy "users can update own profile"
  on public.profiles for update
  to authenticated
  using (id = auth.uid() and public.is_allowed_user())
  with check (id = auth.uid() and public.is_allowed_user());

create policy "users own bags"
  on public.bags for all
  to authenticated
  using (user_id = auth.uid() and public.is_allowed_user())
  with check (user_id = auth.uid() and public.is_allowed_user());

create policy "users own sessions"
  on public.sessions for all
  to authenticated
  using (user_id = auth.uid() and public.is_allowed_user())
  with check (user_id = auth.uid() and public.is_allowed_user());

create policy "users own shots"
  on public.shots for all
  to authenticated
  using (user_id = auth.uid() and public.is_allowed_user())
  with check (user_id = auth.uid() and public.is_allowed_user());

create policy "users own diagnostic events"
  on public.diagnostic_events for all
  to authenticated
  using (user_id = auth.uid() and public.is_allowed_user())
  with check (user_id = auth.uid() and public.is_allowed_user());
