import type { SimReadFinalShotEvent } from '../adapters/simreadFinalShot'

export const simreadFinalShotFixture: SimReadFinalShotEvent = {
  event: 'final-shot',
  timestamp: '2026-05-26T22:15:30.250Z',
  sequence: 7,
  source: 'gspro-range-db',
  rowId: 4321,
  rangeDbTiming: {
    rowId: 4321,
    dateCreated: '2026-05-26 22:15:29',
    emitTimestamp: '2026-05-26T22:15:30.250Z',
    ageMs: 1250,
  },
  resolvedShot: {
    club: '7 Iron',
    carry: 162.4,
    carrySource: 'gspro',
    totalDistance: 169.8,
    totalDistanceSource: 'gspro',
    offline: -6.2,
    offlineSource: 'gspro',
    ballSpeed: 118.5,
    ballSpeedSource: 'gspro',
    vla: 18.3,
    vlaSource: 'gspro',
    hla: -1.1,
    hlaSource: 'gspro',
    spin: 6120,
    spinSource: 'gspro',
    spinAxis: -4.6,
    spinAxisSource: 'gspro',
    peakHeight: 87.3,
    peakHeightSource: 'gspro',
    descentAngle: 46.8,
    descentAngleSource: 'gspro',
    backSpin: 5980,
    sideSpin: -240,
    clubSpeed: 86.1,
    clubPath: 2.4,
    clubAoa: -3.1,
    faceToTarget: 0.8,
    faceToPath: -1.6,
    clubLie: 61.5,
    clubLoft: 34.2,
    dynamicLoft: 29.7,
    closureRate: 5800,
    clubFaceHImpact: -0.12,
    clubFaceVImpact: 0.18,
    smashFactor: 1.38,
    distToPin: 158.6,
  },
  visibleFields: [
    'ballSpeed',
    'backSpin',
    'clubAoa',
    'clubFaceHImpact',
    'clubFaceVImpact',
    'clubLie',
    'clubLoft',
    'clubPath',
    'clubSpeed',
    'closureRate',
    'carryGame',
    'descentAngle',
    'distToPin',
    'dynamicLoft',
    'faceToPath',
    'faceToTarget',
    'hla',
    'offline',
    'peakHeight',
    'sideSpin',
    'smashFactor',
    'spin',
    'spinAxis',
    'totalDistance',
    'vla',
  ],
  ogcEligibility: {
    callable: true,
    recommended: true,
    presentFields: ['ballSpeed', 'vla', 'hla', 'spin', 'spinAxis'],
    missingFields: [],
  },
  layoutSupport: {
    isSupported: true,
    missingRequiredFields: [],
    missingRecommendedFields: [],
  },
}
